# XleRobot Epic 1 生产环境配置
# 多模态在线服务系统配置

production_config:
  # 系统基础配置
  system:
    name: "XleRobot Epic 1"
    version: "1.8.0"
    environment: "production"
    deployment_mode: "blue_green"
    auto_backup: true
    run_demo: true

  # 服务配置
  services:
    asr:
      enabled: true
      provider: "aliyun"
      endpoint: "nls-gateway.cn-shanghai.aliyuncs.com"
      timeout: 30
      retry_count: 3

    tts:
      enabled: true
      provider: "aliyun"
      voice: "xiaoyun"
      rate: 100
      pitch: 50
      volume: 50

    vision:
      enabled: true
      provider: "qwen"
      model: "qwen3-vl-plus"
      max_tokens: 1000

    dialogue:
      enabled: true
      provider: "dashscope"
      model: "qwen3-plus"
      temperature: 0.7

  # 硬件配置
  hardware:
    audio:
      input_device: "default"
      sample_rate: 16000
      channels: 1
      format: "s16le"

    camera:
      enabled: false  # 暂时禁用，因为未检测到摄像头
      device: "/dev/video0"
      resolution: "1920x1080"
      fps: 30

  # 监控配置
  monitoring:
    enabled: true
    metrics_interval: 30
    health_check_interval: 60
    log_level: "INFO"

  # 性能配置
  performance:
    cpu_threshold: 80
    memory_threshold: 85
    disk_threshold: 90
    response_time_threshold: 3000  # ms

  # 安全配置
  security:
    api_key_required: true
    encryption_enabled: true
    access_log_enabled: true

# Epic 1 特定配置
epic1_config:
  phase: "迭代1 - 多模态在线服务"
  stories_completed: 8
  current_story: "Story 1.8 系统优化与部署"
  deployment_status: "complete"
  quality_score: 96.8
  user_satisfaction: 4.35