#!/bin/bash
# XleRobot Epic 1 环境变量设置脚本
# ==================================
#
# 此脚本用于设置XleRobot Epic 1服务所需的环境变量
# 可以选择临时设置或永久设置到shell配置文件
#
# 作者: Dev Agent
# 创建时间: 2025-11-13

set -e

# ============================================
# 🛡️ 加载XLeRobot专用环境配置
# ============================================
# 加载环境脚本，确保使用正确的Python环境
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ -f "$SCRIPT_DIR/xlerobot_env.sh" ]]; then
    source "$SCRIPT_DIR/xlerobot_env.sh"
    echo "✅ XLeRobot环境已加载"
else
    echo "❌ 错误：找不到xlerobot_env.sh环境脚本"
    echo "请确保在XLeRobot项目根目录中运行此脚本"
    exit 1
fi

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 配置
PROJECT_ROOT="/home/sunrise/xlerobot"
ENV_FILE="$PROJECT_ROOT/.env"
BACKUP_DIR="$PROJECT_ROOT/backups"

# 日志函数
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 显示帮助信息
show_help() {
    cat << EOF
XleRobot Epic 1 环境变量设置脚本

用法: $0 [选项]

选项:
    -h, --help      显示此帮助信息
    -t, --temp      临时设置环境变量（当前会话）
    -p, --permanent 永久设置到shell配置文件
    -f, --file      从文件加载环境变量
    -s, --show      显示当前环境变量状态
    -c, --check     检查环境变量配置
    -r, --reset     重置所有环境变量

环境变量说明:
    ALIBABA_CLOUD_ACCESS_KEY_ID     阿里云访问密钥ID
    ALIBABA_CLOUD_ACCESS_KEY_SECRET 阿里云访问密钥Secret
    ALIYUN_NLS_APPKEY               阿里云语音服务AppKey
    PYTHONPATH                      Python模块路径
    ROS_DOMAIN_ID                   ROS2域ID

示例:
    $0 --temp       # 临时设置（推荐测试使用）
    $0 --permanent  # 永久设置（推荐生产使用）
    $0 --show       # 显示当前配置
    $0 --check      # 检查配置

EOF
}

# 创建备份
create_backup() {
    local backup_file="$BACKUP_DIR/env_backup_$(date +%Y%m%d_%H%M%S).sh"
    mkdir -p "$BACKUP_DIR"

    # 备份当前环境变量
    {
        echo "# XleRobot环境变量备份 - $(date)"
        echo "# Generated by setup_environment.sh"
        echo ""

        # 备份已设置的环境变量
        if [ -n "$ALIBABA_CLOUD_ACCESS_KEY_ID" ]; then
            echo "export ALIBABA_CLOUD_ACCESS_KEY_ID='$ALIBABA_CLOUD_ACCESS_KEY_ID'"
        fi
        if [ -n "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" ]; then
            echo "export ALIBABA_CLOUD_ACCESS_KEY_SECRET='$ALIBABA_CLOUD_ACCESS_KEY_SECRET'"
        fi
        if [ -n "$ALIYUN_NLS_APPKEY" ]; then
            echo "export ALIYUN_NLS_APPKEY='$ALIYUN_NLS_APPKEY'"
        fi
        if [ -n "$PYTHONPATH" ]; then
            echo "export PYTHONPATH='$PYTHONPATH'"
        fi
        if [ -n "$ROS_DOMAIN_ID" ]; then
            echo "export ROS_DOMAIN_ID='$ROS_DOMAIN_ID'"
        fi
    } > "$backup_file"

    log_success "备份已创建: $backup_file"
}

# 临时设置环境变量
set_temp_env() {
    log_info "🔧 临时设置环境变量..."

    # 设置阿里云认证信息
    if [ -z "$ALIBABA_CLOUD_ACCESS_KEY_ID" ]; then
        read -p "请输入阿里云Access Key ID: " access_key_id
        if [ -n "$access_key_id" ]; then
            export ALIBABA_CLOUD_ACCESS_KEY_ID="$access_key_id"
            log_success "✅ ALIBABA_CLOUD_ACCESS_KEY_ID 已设置"
        fi
    else
        log_success "✅ ALIBABA_CLOUD_ACCESS_KEY_ID 已存在"
    fi

    if [ -z "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" ]; then
        read -s -p "请输入阿里云Access Key Secret: " access_key_secret
        echo  # 换行
        if [ -n "$access_key_secret" ]; then
            export ALIBABA_CLOUD_ACCESS_KEY_SECRET="$access_key_secret"
            log_success "✅ ALIBABA_CLOUD_ACCESS_KEY_SECRET 已设置"
        fi
    else
        log_success "✅ ALIBABA_CLOUD_ACCESS_KEY_SECRET 已存在"
    fi

    if [ -z "$ALIYUN_NLS_APPKEY" ]; then
        read -p "请输入阿里云NLS AppKey (默认: YOUR_NLS_APPKEY): " appkey
        appkey=${appkey:-"YOUR_NLS_APPKEY"}
        if [ -n "$appkey" ]; then
            export ALIYUN_NLS_APPKEY="$appkey"
            log_success "✅ ALIYUN_NLS_APPKEY 已设置"
        fi
    else
        log_success "✅ ALIYUN_NLS_APPKEY 已存在"
    fi

    # 设置Python路径
    if [ -z "$PYTHONPATH" ]; then
        export PYTHONPATH="$PROJECT_ROOT/src:$PYTHONPATH"
        log_success "✅ PYTHONPATH 已设置"
    else
        if [[ "$PYTHONPATH" != *"$PROJECT_ROOT/src"* ]]; then
            export PYTHONPATH="$PROJECT_ROOT/src:$PYTHONPATH"
            log_success "✅ PYTHONPATH 已更新"
        else
            log_success "✅ PYTHONPATH 已存在"
        fi
    fi

    # 设置ROS域ID
    if [ -z "$ROS_DOMAIN_ID" ]; then
        export ROS_DOMAIN_ID="42"
        log_success "✅ ROS_DOMAIN_ID 已设置"
    else
        log_success "✅ ROS_DOMAIN_ID 已存在"
    fi

    log_success "🎉 临时环境变量设置完成！"
    log_info "⚠️ 注意: 这些环境变量仅在当前会话中有效"
    log_info "💡 提示: 使用 '$0 --permanent' 永久设置"
}

# 永久设置环境变量
set_permanent_env() {
    log_info "🔧 永久设置环境变量..."

    # 确定shell配置文件
    local shell_rc=""
    if [ -n "$ZSH_VERSION" ]; then
        shell_rc="$HOME/.zshrc"
    elif [ -n "$BASH_VERSION" ]; then
        shell_rc="$HOME/.bashrc"
    else
        shell_rc="$HOME/.profile"
    fi

    log_info "检测到shell配置文件: $shell_rc"

    # 创建备份
    if [ -f "$shell_rc" ]; then
        cp "$shell_rc" "$shell_rc.backup.$(date +%Y%m%d_%H%M%S)"
        log_success "已备份原配置文件"
    fi

    # 检查是否已有XleRobot环境变量部分
    local temp_file=$(mktemp)
    if grep -q "# XleRobot Epic 1 Environment Variables" "$shell_rc" 2>/dev/null; then
        log_info "检测到现有XleRobot配置，将更新..."
        # 删除旧的部分
        awk '
            BEGIN { skip = 0 }
            /# XleRobot Epic 1 Environment Variables/ { skip = 1 }
            skip && /^$/ { skip = 0; next }
            !skip { print }
        ' "$shell_rc" > "$temp_file"
    else
        cp "$shell_rc" "$temp_file" 2>/dev/null || touch "$temp_file"
    fi

    # 添加新的环境变量部分
    cat >> "$temp_file" << 'EOF'

# XleRobot Epic 1 Environment Variables
# Generated by setup_environment.sh
if [ -f "/home/sunrise/xlerobot/.env" ]; then
    set -a
    source /home/sunrise/xlerobot/.env
    set +a
fi

# Set default values if not set in .env
export ALIBABA_CLOUD_ACCESS_KEY_ID="${ALIBABA_CLOUD_ACCESS_KEY_ID:-}"
export ALIBABA_CLOUD_ACCESS_KEY_SECRET="${ALIBABA_CLOUD_ACCESS_KEY_SECRET:-}"
export ALIYUN_NLS_APPKEY="${ALIYUN_NLS_APPKEY:-YOUR_NLS_APPKEY}"
export PYTHONPATH="${PYTHONPATH:-/home/sunrise/xlerobot/src}"
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-42}"
EOF

    # 应用配置
    mv "$temp_file" "$shell_rc"

    # 创建.env文件模板
    create_env_file

    log_success "✅ 永久环境变量配置完成！"
    log_info "📁 配置已写入: $shell_rc"
    log_info "🔧 请运行 'source $shell_rc' 或重新打开终端以使配置生效"
}

# 创建.env文件
create_env_file() {
    log_info "📝 创建.env文件模板..."

    cat > "$ENV_FILE" << 'EOF'
# XleRobot Epic 1 环境变量配置文件
# 请填入您的实际配置信息
# 注意: 请不要将此文件提交到版本控制系统

# 阿里云访问密钥 (必填)
ALIBABA_CLOUD_ACCESS_KEY_ID=
ALIBABA_CLOUD_ACCESS_KEY_SECRET=

# 阿里云语音服务AppKey (已提供默认值)
ALIYUN_NLS_APPKEY=YOUR_NLS_APPKEY

# 其他配置 (通常不需要修改)
PYTHONPATH=/home/sunrise/xlerobot/src
ROS_DOMAIN_ID=42
EOF

    log_success "✅ .env文件模板已创建: $ENV_FILE"
    log_warning "⚠️ 请编辑 $ENV_FILE 文件，填入您的阿里云访问密钥"
}

# 显示当前环境变量
show_env_status() {
    log_info "📊 当前环境变量状态:"
    echo "=================================="

    # 检查每个环境变量
    local vars=(
        "ALIBABA_CLOUD_ACCESS_KEY_ID:阿里云访问密钥ID"
        "ALIBABA_CLOUD_ACCESS_KEY_SECRET:阿里云访问密钥Secret"
        "ALIYUN_NLS_APPKEY:阿里云语音服务AppKey"
        "PYTHONPATH:Python模块路径"
        "ROS_DOMAIN_ID:ROS2域ID"
    )

    for var_info in "${vars[@]}"; do
        local var_name=$(echo "$var_info" | cut -d':' -f1)
        local var_desc=$(echo "$var_info" | cut -d':' -f2)
        local var_value="${!var_name}"

        if [ -n "$var_value" ]; then
            if [[ "$var_name" == *"KEY"* ]] || [[ "$var_name" == *"SECRET"* ]]; then
                # 敏感信息，只显示前几位
                local display_value="${var_value:0:10}..."
            else
                local display_value="$var_value"
            fi
            log_success "✅ $var_name: $display_value"
        else
            log_warning "⚠️ $var_name: 未设置"
        fi
    done

    echo "=================================="

    # 检查.env文件
    if [ -f "$ENV_FILE" ]; then
        log_info "📁 .env文件存在"
        if [ -s "$ENV_FILE" ]; then
            local filled_vars=$(grep -v "^#" "$ENV_FILE" | grep -v "^$" | grep -c "=" || true)
            log_info "📝 .env文件中有 $filled_vars 个变量配置"
        else
            log_warning "⚠️ .env文件为空"
        fi
    else
        log_warning "⚠️ .env文件不存在"
    fi
}

# 检查环境变量配置
check_env_config() {
    log_info "🔍 检查环境变量配置..."

    local errors=0
    local warnings=0

    # 检查必需的环境变量
    if [ -z "$ALIBABA_CLOUD_ACCESS_KEY_ID" ]; then
        log_error "❌ ALIBABA_CLOUD_ACCESS_KEY_ID 未设置"
        ((errors++))
    else
        log_success "✅ ALIBABA_CLOUD_ACCESS_KEY_ID 已设置"
    fi

    if [ -z "$ALIBABA_CLOUD_ACCESS_KEY_SECRET" ]; then
        log_error "❌ ALIBABA_CLOUD_ACCESS_KEY_SECRET 未设置"
        ((errors++))
    else
        log_success "✅ ALIBABA_CLOUD_ACCESS_KEY_SECRET 已设置"
    fi

    if [ -z "$ALIYUN_NLS_APPKEY" ]; then
        log_warning "⚠️ ALIYUN_NLS_APPKEY 未设置，将使用默认值"
        ((warnings++))
    else
        log_success "✅ ALIYUN_NLS_APPKEY 已设置"
    fi

    # 检查可选的环境变量
    if [ -z "$PYTHONPATH" ]; then
        log_warning "⚠️ PYTHONPATH 未设置，可能影响模块导入"
        ((warnings++))
    else
        if [[ "$PYTHONPATH" == *"$PROJECT_ROOT/src"* ]]; then
            log_success "✅ PYTHONPATH 正确配置"
        else
            log_warning "⚠️ PYTHONPATH 可能未包含项目路径"
            ((warnings++))
        fi
    fi

    if [ -z "$ROS_DOMAIN_ID" ]; then
        log_warning "⚠️ ROS_DOMAIN_ID 未设置，将使用默认值"
        ((warnings++))
    else
        log_success "✅ ROS_DOMAIN_ID 已设置"
    fi

    # 总结
    echo "=================================="
    if [ $errors -gt 0 ]; then
        log_error "❌ 配置检查失败: $errors 个错误，$warnings 个警告"
        log_info "请使用 '$0 --temp' 或 '$0 --permanent' 设置缺失的环境变量"
        return 1
    elif [ $warnings -gt 0 ]; then
        log_warning "⚠️ 配置基本正常: $warnings 个警告"
        log_info "建议解决警告问题以获得最佳体验"
        return 0
    else
        log_success "🎉 配置检查完全通过！"
        return 0
    fi
}

# 重置环境变量
reset_env() {
    log_warning "⚠️ 重置所有XleRobot相关环境变量..."

    # 创建备份
    create_backup

    # 清理当前环境变量
    unset ALIBABA_CLOUD_ACCESS_KEY_ID
    unset ALIBABA_CLOUD_ACCESS_KEY_SECRET
    unset ALIYUN_NLS_APPKEY
    unset ROS_DOMAIN_ID

    # 清理PYTHONPATH中的项目路径
    if [ -n "$PYTHONPATH" ]; then
        export PYTHONPATH=$(echo "$PYTHONPATH" | sed "s|$PROJECT_ROOT/src:||g" | sed "s|:$PROJECT_ROOT/src||g")
    fi

    # 删除.env文件
    if [ -f "$ENV_FILE" ]; then
        rm -f "$ENV_FILE"
        log_info "已删除 .env 文件"
    fi

    # 清理shell配置文件中的XleRobot配置
    local shell_rc=""
    if [ -n "$ZSH_VERSION" ]; then
        shell_rc="$HOME/.zshrc"
    elif [ -n "$BASH_VERSION" ]; then
        shell_rc="$HOME/.bashrc"
    else
        shell_rc="$HOME/.profile"
    fi

    if [ -f "$shell_rc" ]; then
        local temp_file=$(mktemp)
        awk '
            BEGIN { skip = 0 }
            /# XleRobot Epic 1 Environment Variables/ { skip = 1 }
            skip && /^$/ { skip = 0; next }
            !skip { print }
        ' "$shell_rc" > "$temp_file"
        mv "$temp_file" "$shell_rc"
        log_info "已清理 shell 配置文件"
    fi

    log_success "✅ 环境变量重置完成"
}

# 主函数
main() {
    case "${1:-help}" in
        "temp"|"-t"|"--temp")
            set_temp_env
            ;;
        "permanent"|"-p"|"--permanent")
            set_permanent_env
            ;;
        "file"|"-f"|"--file")
            if [ -f "$ENV_FILE" ]; then
                log_info "从 .env 文件加载环境变量..."
                set -a
                source "$ENV_FILE"
                set +a
                log_success "✅ 环境变量已加载"
            else
                log_error "❌ .env 文件不存在"
                exit 1
            fi
            ;;
        "show"|"-s"|"--show")
            show_env_status
            ;;
        "check"|"-c"|"--check")
            check_env_config
            ;;
        "reset"|"-r"|"--reset")
            reset_env
            ;;
        "help"|"-h"|"--help")
            show_help
            ;;
        *)
            log_error "未知选项: $1"
            show_help
            exit 1
            ;;
    esac
}

# 执行主函数
main "$@"